### ISSUE TITLE
When clicking the back button on the Shopping list page, a blank page appears

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#17]
![Image](https://github.com/user-attachments/assets/64ff32df-27df-4adf-a964-453e2f38cd51)

**Comment by taitdigital** [comment]
couldn't repoduce.

It could be cache thing we know this happens, try to reproduce it again but have the dev tool open. and see if theres any kind of error to look at. try to take note of anything you might have done before hand. @jody-tait

**Comment by jody-tait** [comment]
Only way I've been able to recreate this, is by pressing back after pasting the link into a new tab, so there isn't anywhere to go "back" to:

![Image](https://github.com/user-attachments/assets/d01cb5c3-8e90-4392-95dc-18456b43e67b)

I don't think this is something that many if any people will be able to recreate live so will close for now and see if it comes back again.
