### ISSUE TITLE
Meal Plans - Date calculations using number of days

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#19]
"The end date is calculated if a start date and number of days has been entered"

Open Create a meal plan dialog
Enter start date
Cannot enter a number of days so end date cannot calculate

Can enter total number of days, but then there are no dates attached.

Unsure if this is actually how this is meant to work? i.e.

EITHER - a date range, OR
a number of days with no date range?

May just need to update test plan

**Comment by taitdigital** [comment]
@jody-tait yes I've put a little divider with the word OR.

the idea was to either made it for a date range or just a number of days and that after creation it can be rescheduled as many times as you want.

my thought were someone whos curating / publishing mealplans would choose the number of days, and other users would be able to copy those plans into their accounts.

maybe there is a better wa to convey its one or the other in the UI?

**Comment by jody-tait** [comment]
Let's leave it for now and see how people use it / question it
