### ISSUE TITLE
Removing Shared list - missing name in header of dialog

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#2]
"The list name is displayed in the dialog header"

When removing a shared list it states Remove undefined from shared lists.

As you can see from the screenshot, the attempt was to delete "Jody Test - Edit" shopping list

![Image](https://github.com/user-attachments/assets/f8d233d4-ce4e-4bbe-8043-454907268a44)

**Comment by taitdigital** [comment]
couldn't reproduce this one

**Comment by jody-tait** [comment]
Now a pass
