### ISSUE TITLE
Can create a Shopping List with non alphanumeric characters in it

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#4]
"The name input does not accept unsafe characters (alphanumeric with slash and dash only)"

Click Create
Typed a series of non-alphanumeric symbols
Click Create
Shopping list created

![Image](https://github.com/user-attachments/assets/c56c1fb2-a0ef-4ec9-a054-aaf8b0a29baf)

**Comment by jody-tait** [comment]
Now a pass
