### ISSUE TITLE
Get Enlighten to Update the mail record

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#51]
We need enlighten to provide the right IP address for the rest of the mail records. 

I have changed the DNS management to them as well so this way support can just do that for us without waiting on me.

**Records to update**

- [ ] mail - ip address of the mail exchange, we use this to send emails from the app via mail.taitdigital.co.nz

- [ ] webmail & www.webmail - just so we can be all professional like and access our webmail from webmail.taitdigital.co.nz

- [ ] mailboxes & www.mailboxes - the previous host had a back up webmail server this can probably just be deleted 

**expected config for our app configuration when done:**

MAIL_MAILER=smtp
MAIL_HOST=mail.taitdigital.co.nz
MAIL_PORT=587

**Comment by jody-tait** [comment]
Have emailed Enlighten
