### ISSUE TITLE
Shared Lists - no error for invalid email address

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#7]
"The text input displays an error if there is an invalid email address"

Open dialog box using stacked dots
Click Share
Typed various different incorrect email address formats.
Click Add
Text appears on the shared list

Can also click add with no text in it at all and it will add a line

![Image](https://github.com/user-attachments/assets/0de305fc-3801-487f-9751-736192aa5c87)

"Failed to Share" does seem to appear as a notification, but it disappears very quickly

![Image](https://github.com/user-attachments/assets/8817bfc5-8e52-420a-ac34-dfd79398235f)

**Comment by jody-tait** [comment]
Now a pass
