### ISSUE TITLE
Dialog does not close when entering shop mode - Shopping Lists

### ISSUE THREAD

**Issue by taitdigital** [taitdigital/aisle-nine-beta#8]
"Pressing Shop navigates to the list detail page in shop mode"

Click on eye icon to enter shopping list
Click on stacked dots icon
Click on shop
Shopping list does enter into shopping mode, but dialog box does not disappear like it does doing the same from the main view

This is the case for both Owned Shopping Lists, and Shared Shopping Lists

![Image](https://github.com/user-attachments/assets/6eaba2fc-be54-4b71-a5f7-e24e87535441)

**Comment by jody-tait** [comment]
Now a pass
